# -*- coding: utf-8 -*-
"""BNair_Lab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jrojti_c2rv5VUqos24oGyyWGbfJu5HG
"""

"""
ECG Classification with Parameter-Efficient Fine-Tuning (PEFT)

This script trains and evaluates 6 model configurations:
- Wav2Vec2 (Adapter & LoRA)
- HuBERT (Adapter & LoRA)
- ECG-FM (Adapter & LoRA)

All models use frozen pre-trained backbones with minimal trainable parameters.
"""

import os, warnings, random, math, types, zipfile
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix, roc_auc_score
from transformers import AutoProcessor, AutoConfig, AutoFeatureExtractor, Wav2Vec2Model, Wav2Vec2ForSequenceClassification, HubertModel, HubertForSequenceClassification
from peft import LoraConfig, get_peft_model
from copy import deepcopy
from itertools import product

warnings.filterwarnings("ignore")

# Reproducibility
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

# Device setup
dev = torch.device("cuda" if torch.cuda.is_available() else "mps" if hasattr(torch.backends, "mps") and torch.backends.mps.is_available() else "cpu")
print(f"Using device: {dev}")

# Directory structure
base = "/content"
data_dir = os.path.join(base, 'data')
plot_dir = os.path.join(base, 'plots')
met_dir = os.path.join(base, 'metrics')
hist_dir = os.path.join(base, 'histories')
for d in [data_dir, plot_dir, met_dir, hist_dir]:
    os.makedirs(d, exist_ok=True)

# Hyperparameter configurations for tuning
HP_CONFIG = {
    'batch_sizes': [32, 64],
    'learning_rates_adapter': [5e-5, 1e-4],
    'learning_rates_lora': [2.5e-5, 5e-5],
    'epochs': [10],
    'weight_decays': [1e-4, 1e-3],
    'patience': [3],
    'lora_ranks': [8, 16],
    'adapter_hiddens': [256, 512]
}

# Set to True to run hyperparameter search before main training
TUNING_MODE = False

# Data Loading & Preprocessing


# Handle both zipped and unzipped CSV
zip_path = "/content/df_segment2.csv.zip"
csv_path = os.path.join(data_dir, "df_segment2.csv")

if os.path.exists(zip_path) and not os.path.exists(csv_path):
    print(f"Extracting {zip_path}...")
    with zipfile.ZipFile(zip_path, 'r') as zf:
        zf.extractall(data_dir)
    print(f"Extracted to {data_dir}")

if not os.path.exists(csv_path):
    csv_path = "/content/df_segment2.csv"
    print(f"Using: {csv_path}")

def save_fig(fig, name, subdir=plot_dir, dpi=150):
    """Save matplotlib figure as PNG"""
    os.makedirs(subdir, exist_ok=True)
    p = os.path.join(subdir, f"{name.replace(' ', '_').replace('/', '_')}.png")
    fig.savefig(p, bbox_inches='tight', dpi=dpi)
    print(f"[saved] {p}")

def save_met(m, name, subdir=met_dir):
    """Save metrics dictionary as CSV"""
    os.makedirs(subdir, exist_ok=True)
    p = os.path.join(subdir, f"{name.replace(' ', '_').replace('/', '_')}.csv")
    pd.DataFrame([m]).to_csv(p, index=False)
    print(f"[saved] {p}")

def save_hist(hist, name, subdir=hist_dir):
    """Save training history as CSV"""
    os.makedirs(subdir, exist_ok=True)
    p = os.path.join(subdir, f"{name.replace(' ', '_').replace('/', '_')}.csv")
    pd.DataFrame(hist).to_csv(p, index=False)
    print(f"[saved history] {p}")

# Load dataset (601 columns: 600 features + 1 label)
df = pd.read_csv(csv_path, header=None)
assert df.shape[1] == 601, f"Expected 601 columns, got {df.shape[1]}"

X = df.iloc[:, :-1].astype(np.float32).values  # Features
y = df.iloc[:, -1].astype(int).values          # Labels (0/1)
print(f"Data loaded: {X.shape}, Labels: {y.shape}, Distribution: {np.bincount(y)}")

# Row-wise z-score normalization (each ECG signal normalized independently)
rm = X.mean(axis=1, keepdims=True)
rs = X.std(axis=1, keepdims=True)
rs[rs == 0] = 1.0  # Avoid division by zero
X = (X - rm) / rs

# Stratified train/val/test split (70/15/15)
X_tr, X_tmp, y_tr, y_tmp = train_test_split(X, y, test_size=0.30, random_state=SEED, stratify=y)
X_val, X_te, y_val, y_te = train_test_split(X_tmp, y_tmp, test_size=0.50, random_state=SEED, stratify=y_tmp)
print(f"Splits: Train={X_tr.shape[0]}, Val={X_val.shape[0]}, Test={X_te.shape[0]}")


# Dataset & Preprocessing


TL = 1000  

def interp(x, tl):
    """Linear interpolation from original length to target length"""
    sl = x.shape[0]
    if sl == tl:
        return x
    xp = np.linspace(0, 1, num=sl, dtype=np.float32)
    xn = np.linspace(0, 1, num=tl, dtype=np.float32)
    return np.interp(xn, xp, x.astype(np.float32)).astype(np.float32)

class DS(Dataset):
    """ECG Dataset with automatic resampling to target length"""
    def __init__(self, X, y, tl=TL):
        self.X, self.y, self.tl = X, y, tl

    def __len__(self):
        return len(self.X)

    def __getitem__(self, i):
        wave = interp(self.X[i], self.tl)
        return torch.from_numpy(wave), torch.tensor(self.y[i], dtype=torch.long)

# Create datasets
ds_tr = DS(X_tr, y_tr)
ds_val = DS(X_val, y_val)
ds_te = DS(X_te, y_te)

def zs(x):
    """Per-row z-score normalization for batches"""
    m = x.mean(dim=1, keepdim=True)
    s = x.std(dim=1, unbiased=False, keepdim=True).clamp_min(1e-6)
    return (x - m) / s

def up(x1d, tl=TL):
    """Upsample 1D signal using linear interpolation"""
    x = x1d.view(1, 1, -1)
    y = F.interpolate(x, size=tl, mode="linear", align_corners=False)
    return y.view(-1)

def to_inp(sigs, labs, proc):
    """
    Convert ECG signals to audio model inputs

    Args:
        sigs: List of ECG signal arrays
        labs: List of labels
        proc: HuggingFace processor (handles padding, attention masks)

    Returns:
        Dict with input_values, attention_mask, and labels
    """
    B = len(sigs)
    x = torch.stack([torch.as_tensor(s, dtype=torch.float32) for s in sigs], dim=0)
    x = zs(x)  # Normalize
    x = torch.stack([up(r) for r in x], dim=0)  # Resample
    p = proc(x.numpy(), sampling_rate=16000, return_tensors="pt", padding=True)
    return {
        "input_values": p["input_values"],
        "attention_mask": p.get("attention_mask", None),
        "labels": torch.as_tensor(labs, dtype=torch.float32)
    }

# Metrics & Evaluation

def comp_met(yt, yp):
    """
    Compute classification metrics

    Args:
        yt: True labels
        yp: Predicted probabilities

    Returns:
        Dict with acc, precision, recall, f1, auc, confusion matrix
    """
    yt = np.asarray(yt).astype(int)
    yp = np.asarray(yp).astype(float)
    pred = (yp >= 0.5).astype(int)

    acc = accuracy_score(yt, pred)
    prec, rec, f1, _ = precision_recall_fscore_support(yt, pred, average="binary", zero_division=0)

    try:
        auc = roc_auc_score(yt, yp) if len(np.unique(yt)) > 1 else float("nan")
    except:
        auc = float("nan")

    cm = confusion_matrix(yt, pred)

    return {"acc": acc, "precision": prec, "recall": rec, "f1": f1, "auc": auc, "cm": cm}

def mv(x, d):
    """Recursively move tensors/dicts/lists to device"""
    if isinstance(x, torch.Tensor):
        return x.to(d)
    if isinstance(x, dict):
        return {k: mv(v, d) for k, v in x.items() if v is not None}
    if isinstance(x, (list, tuple)):
        return type(x)(mv(v, d) for v in x)
    return x

def b2il(b, d):
    """Convert batch to inputs dict and labels tensor"""
    if isinstance(b, dict):
        l = b["labels"]
        inp = {k: v for k, v in b.items() if k != "labels"}
        return mv(inp, d), l.to(d).float()

    if isinstance(b, (list, tuple)) and len(b) == 2:
        a, c = b
        if isinstance(a, dict):
            return mv(a, d), c.to(d).float()
        else:
            return mv({"input_values": a}, d), c.to(d).float()

    raise ValueError("Unexpected batch format")

# Training & Evaluation
def train(mdl, proc, tr_ld, vl_ld, d, lr=5e-5, ep=5, wd=1e-4, pat=2, verbose=True):
    """
    Train model with early stopping and metric tracking

    Args:
        mdl: PyTorch model
        proc: Preprocessor/processor
        tr_ld: Train dataloader
        vl_ld: Validation dataloader
        d: Device
        lr: Learning rate
        ep: Max epochs
        wd: Weight decay
        pat: Early stopping patience
        verbose: Print training progress

    Returns:
        Trained model and history dict
    """
    mdl = mdl.to(d)
    opt = AdamW((p for p in mdl.parameters() if p.requires_grad), lr=lr, weight_decay=wd)
    bv, bs, ni = float("inf"), None, 0

    # Track metrics per epoch
    history = {
        'epoch': [],
        'train_loss': [],
        'val_loss': [],
        'val_acc': [],
        'val_precision': [],
        'val_recall': [],
        'val_f1': [],
        'val_auc': []
    }

    if verbose:
        print(f"\nTraining: lr={lr}, epochs={ep}, wd={wd}, patience={pat}")

    for e in range(1, ep + 1):
        # Training phase
        mdl.train()
        rl = 0.0
        for bi, b in enumerate(tr_ld):
            inp, lab = b2il(b, d)
            opt.zero_grad(set_to_none=True)
            out = mdl(**inp, labels=lab)
            out.loss.backward()
            opt.step()
            rl += out.loss.item()

            if verbose and (bi + 1) % 10 == 0:
                print(f"  Epoch {e}/{ep} Batch {bi+1}/{len(tr_ld)} Loss: {out.loss.item():.4f}")

        tl = rl / max(1, len(tr_ld))

        # Validation phase
        mdl.eval()
        vl = 0.0
        with torch.no_grad():
            for b in vl_ld:
                inp, lab = b2il(b, d)
                out = mdl(**inp, labels=lab)
                vl += out.loss.item()
        vl /= max(1, len(vl_ld))

        # Compute validation metrics
        vm = eval_mdl(mdl, proc, vl_ld, d)

        # Store history
        history['epoch'].append(e)
        history['train_loss'].append(tl)
        history['val_loss'].append(vl)
        history['val_acc'].append(vm['acc'])
        history['val_precision'].append(vm['precision'])
        history['val_recall'].append(vm['recall'])
        history['val_f1'].append(vm['f1'])
        history['val_auc'].append(vm['auc'])

        if verbose:
            print(f"  Epoch {e}/{ep} TrLoss: {tl:.4f} VaLoss: {vl:.4f} VaAcc: {vm['acc']:.4f} VaF1: {vm['f1']:.4f}")

        # Early stopping
        if vl < bv - 1e-6:
            bv = vl
            bs = deepcopy({k: v.detach().cpu() for k, v in mdl.state_dict().items()})
            ni = 0
            if verbose:
                print(f"  Best validation loss: {bv:.4f}")
        else:
            ni += 1
            if verbose:
                print(f"  No improvement for {ni} epoch(s)")
            if ni >= pat:
                if verbose:
                    print("  Early stopping triggered")
                break

    # Restore best model
    if bs is not None:
        mdl.load_state_dict(bs)
        mdl.to(d)
        if verbose:
            print(f"Loaded best model (val_loss={bv:.4f})")

    return mdl, history

def eval_mdl(mdl, proc, ld, d):
    """Evaluate model and return metrics"""
    mdl.eval()
    ap, al = [], []

    with torch.no_grad():
        for b in ld:
            inp, lab = b2il(b, d)
            out = mdl(**inp)
            lg = out.logits if hasattr(out, "logits") else out
            pr = torch.sigmoid(lg.squeeze(-1))
            ap.append(pr.detach().cpu())
            al.append(lab.detach().cpu())

    yp = torch.cat(ap, dim=0).numpy()
    yt = torch.cat(al, dim=0).numpy().astype(int)

    return comp_met(yt, yp)


# Visualization


def plot_training_curves(hist, model_name):
    """Plot training curves (loss, acc, f1, auc) for a single model"""
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))

    epochs = hist['epoch']

    # Loss curves
    axes[0, 0].plot(epochs, hist['train_loss'], 'b-', label='Train Loss', linewidth=2)
    axes[0, 0].plot(epochs, hist['val_loss'], 'r-', label='Val Loss', linewidth=2)
    axes[0, 0].set_xlabel('Epoch', fontsize=12)
    axes[0, 0].set_ylabel('Loss', fontsize=12)
    axes[0, 0].set_title('Training & Validation Loss', fontsize=14, fontweight='bold')
    axes[0, 0].legend()
    axes[0, 0].grid(True, alpha=0.3)

    # Accuracy
    axes[0, 1].plot(epochs, hist['val_acc'], 'g-', label='Val Accuracy', linewidth=2)
    axes[0, 1].set_xlabel('Epoch', fontsize=12)
    axes[0, 1].set_ylabel('Accuracy', fontsize=12)
    axes[0, 1].set_title('Validation Accuracy', fontsize=14, fontweight='bold')
    axes[0, 1].legend()
    axes[0, 1].grid(True, alpha=0.3)

    # F1 Score
    axes[1, 0].plot(epochs, hist['val_f1'], 'm-', label='Val F1', linewidth=2)
    axes[1, 0].set_xlabel('Epoch', fontsize=12)
    axes[1, 0].set_ylabel('F1 Score', fontsize=12)
    axes[1, 0].set_title('Validation F1 Score', fontsize=14, fontweight='bold')
    axes[1, 0].legend()
    axes[1, 0].grid(True, alpha=0.3)

    # AUC
    axes[1, 1].plot(epochs, hist['val_auc'], 'c-', label='Val AUC', linewidth=2)
    axes[1, 1].set_xlabel('Epoch', fontsize=12)
    axes[1, 1].set_ylabel('AUC', fontsize=12)
    axes[1, 1].set_title('Validation AUC', fontsize=14, fontweight='bold')
    axes[1, 1].legend()
    axes[1, 1].grid(True, alpha=0.3)

    plt.suptitle(f'{model_name} - Training History', fontsize=16, fontweight='bold', y=1.00)
    plt.tight_layout()
    save_fig(fig, f"{model_name}_curves")
    plt.close()

def plot_comparison_curves(all_histories, metric='val_acc'):
    """Plot comparison of a single metric across all models"""
    fig, ax = plt.subplots(figsize=(12, 6))

    for name, hist in all_histories.items():
        ax.plot(hist['epoch'], hist[metric], label=name, linewidth=2, marker='o', markersize=4)

    ax.set_xlabel('Epoch', fontsize=12)
    ax.set_ylabel(metric.replace('_', ' ').title(), fontsize=12)
    ax.set_title(f'All Models - {metric.replace("_", " ").title()} Comparison', fontsize=14, fontweight='bold')
    ax.legend(loc='best')
    ax.grid(True, alpha=0.3)

    plt.tight_layout()
    save_fig(fig, f"comparison_{metric}")
    plt.close()


# Model Architectures


# Load pre-trained processors
wm = "facebook/wav2vec2-base"
pw = AutoProcessor.from_pretrained(wm, do_normalize=True, return_attention_mask=True)

hm = "facebook/hubert-base-ls960"
ph = AutoFeatureExtractor.from_pretrained(hm, do_normalize=True, return_attention_mask=True)

# Collate functions
def cf_w(b):
    s, l = zip(*b)
    return to_inp(s, l, pw)

def cf_h(b):
    s, l = zip(*b)
    return to_inp(s, l, ph)

# Load frozen encoders
enc_w = Wav2Vec2Model.from_pretrained(wm)
for p in enc_w.parameters():
    p.requires_grad = False

enc_h = HubertModel.from_pretrained(hm)
for p in enc_h.parameters():
    p.requires_grad = False

class W2VA(nn.Module):
    """Wav2Vec2 with Adapter-style classifier head (frozen backbone)"""
    def __init__(self, enc, h=256, pd=0.1):
        super().__init__()
        self.enc = enc
        hs = self.enc.config.hidden_size
        self.head = nn.Sequential(
            nn.Linear(hs, h),
            nn.ReLU(),
            nn.Dropout(pd),
            nn.Linear(h, 1)
        )

    def forward(self, input_values, attention_mask=None, labels=None):
        out = self.enc(input_values=input_values, attention_mask=attention_mask, return_dict=True)
        hid = out.last_hidden_state

        # Use downsampled mask if available
        fm = getattr(out, "extractor_attention_mask", None)
        if fm is None and attention_mask is not None:
            T = hid.size(1)
            fm = F.interpolate(attention_mask[:, None, :].float(), size=T, mode="nearest").squeeze(1)

        # Mask-aware pooling
        if fm is not None:
            msk = fm.unsqueeze(-1).type_as(hid)
            pool = (hid * msk).sum(dim=1) / msk.sum(dim=1).clamp_min(1e-6)
        else:
            pool = hid.mean(dim=1)

        lg = self.head(pool)

        if labels is not None:
            l = labels.unsqueeze(1).to(lg.dtype)
            loss = F.binary_cross_entropy_with_logits(lg, l)
            return type("O", (), {"loss": loss, "logits": lg})
        return type("O", (), {"logits": lg})

class HBA(nn.Module):
    """HuBERT with Adapter-style classifier head (frozen backbone)"""
    def __init__(self, enc, h=256, pd=0.1):
        super().__init__()
        self.enc = enc
        hs = self.enc.config.hidden_size
        self.head = nn.Sequential(
            nn.Linear(hs, h),
            nn.ReLU(),
            nn.Dropout(pd),
            nn.Linear(h, 1)
        )

    def forward(self, input_values, attention_mask=None, labels=None):
        out = self.enc(input_values=input_values, attention_mask=attention_mask, return_dict=True)
        hid = out.last_hidden_state

        fm = getattr(out, "extractor_attention_mask", None)
        if fm is None and attention_mask is not None:
            T = hid.size(1)
            fm = F.interpolate(attention_mask[:, None, :].float(), size=T, mode="nearest").squeeze(1)

        if fm is not None:
            msk = fm.unsqueeze(-1).type_as(hid)
            pool = (hid * msk).sum(dim=1) / msk.sum(dim=1).clamp_min(1e-6)
        else:
            pool = hid.mean(dim=1)

        lg = self.head(pool)

        if labels is not None:
            l = labels.unsqueeze(1).to(lg.dtype)
            loss = F.binary_cross_entropy_with_logits(lg, l)
            return type("O", (), {"loss": loss, "logits": lg})
        return type("O", (), {"logits": lg})

def noop(self):
    """No-op function to prevent PEFT issues with audio models"""
    return

class ECGB(nn.Module):
    """Simple CNN backbone for ECG-FM (fallback if checkpoint unavailable)"""
    def __init__(self, ic=1, h=128):
        super().__init__()
        self.feat = nn.Sequential(
            nn.Conv1d(ic, 64, 7, stride=2, padding=3), nn.ReLU(),
            nn.Conv1d(64, 128, 7, stride=2, padding=3), nn.ReLU(),
            nn.Conv1d(128, h, 7, stride=2, padding=3), nn.ReLU()
        )
        self.config = types.SimpleNamespace(hidden_size=h)

    def forward(self, x):
        if x.dim() == 2:
            x = x.unsqueeze(1)
        h = self.feat(x)
        h = h.transpose(1, 2).contiguous()
        return types.SimpleNamespace(last_hidden_state=h, extractor_attention_mask=None)

def load_ecg(cp, d):
    """Load ECG-FM backbone from checkpoint if available"""
    bb = ECGB()
    if os.path.isfile(cp):
        try:
            obj = torch.load(cp, map_location="cpu")
            sd = obj.get("state_dict", obj) if isinstance(obj, dict) else obj
            bb.load_state_dict(sd, strict=False)
            print("Loaded ECG-FM checkpoint")
        except Exception as e:
            print(f"Could not load checkpoint: {e}")
    else:
        print("No checkpoint found - using random init")
    return bb.to(d)

class ECA(nn.Module):
    """ECG-FM with Adapter-style classifier head"""
    def __init__(self, bb, h=256, pd=0.1):
        super().__init__()
        self.enc = bb
        for p in self.enc.parameters():
            p.requires_grad = False

        # Infer hidden dimension
        hd = getattr(self.enc, "config", types.SimpleNamespace(hidden_size=None)).hidden_size
        if hd is None:
            with torch.no_grad():
                dm = torch.zeros(2, 1000)
                out = self.enc(dm)
                hd = out.last_hidden_state.size(-1)

        self.head = nn.Sequential(
            nn.Linear(hd, h),
            nn.ReLU(),
            nn.Dropout(pd),
            nn.Linear(h, 1)
        )

    def forward(self, input_values, attention_mask=None, labels=None):
        out = self.enc(input_values)
        hid = out.last_hidden_state

        fm = getattr(out, "extractor_attention_mask", None)
        if fm is None and attention_mask is not None:
            T = hid.size(1)
            fm = F.interpolate(attention_mask[:, None, :].float(), size=T, mode="nearest").squeeze(1)

        if fm is not None:
            msk = fm.unsqueeze(-1).type_as(hid)
            pool = (hid * msk).sum(dim=1) / msk.sum(dim=1).clamp_min(1e-6)
        else:
            pool = hid.mean(dim=1)

        lg = self.head(pool)

        if labels is not None:
            l = labels.unsqueeze(1).to(lg.dtype)
            loss = F.binary_cross_entropy_with_logits(lg, l)
            return types.SimpleNamespace(loss=loss, logits=lg)
        return types.SimpleNamespace(logits=lg)

class LRL(nn.Module):
    """LoRA Linear layer wrapper"""
    def __init__(self, bl, r=8, a=16, d=0.05):
        super().__init__()
        self.base = bl
        for p in self.base.parameters():
            p.requires_grad = False

        self.r, self.scale = r, a / float(r)
        self.lora_A = nn.Linear(self.base.in_features, r, bias=False)
        self.lora_B = nn.Linear(r, self.base.out_features, bias=False)
        self.drop = nn.Dropout(d)

        # Standard LoRA initialization
        nn.init.kaiming_uniform_(self.lora_A.weight, a=math.sqrt(5))
        nn.init.zeros_(self.lora_B.weight)

    def forward(self, x):
        return self.base(x) + self.drop(self.lora_B(self.lora_A(x))) * self.scale

def apply_lora(mod, r=8, a=16, d=0.05):
    """Recursively inject LoRA into all Linear layers"""
    for n, c in list(mod.named_children()):
        if isinstance(c, nn.Linear):
            setattr(mod, n, LRL(c, r=r, a=a, d=d))
        else:
            apply_lora(c, r=r, a=a, d=d)

class ECL(nn.Module):
    """ECG-FM with LoRA fine-tuning"""
    def __init__(self, bb, h=256, pd=0.1, r=8, a=16, ld=0.05):
        super().__init__()
        self.enc = bb
        for p in self.enc.parameters():
            p.requires_grad = False

        # Inject LoRA
        apply_lora(self.enc, r=r, a=a, d=ld)

        # Infer hidden dimension
        hd = getattr(self.enc, "config", types.SimpleNamespace(hidden_size=None)).hidden_size
        if hd is None:
            with torch.no_grad():
                dm = torch.zeros(2, 1000)
                out = self.enc(dm)
                hd = out.last_hidden_state.size(-1)

        self.head = nn.Sequential(
            nn.Linear(hd, h),
            nn.ReLU(),
            nn.Dropout(pd),
            nn.Linear(h, 1)
        )

    def forward(self, input_values, attention_mask=None, labels=None):
        out = self.enc(input_values)
        hid = out.last_hidden_state

        fm = getattr(out, "extractor_attention_mask", None)
        if fm is None and attention_mask is not None:
            T = hid.size(1)
            fm = F.interpolate(attention_mask[:, None, :].float(), size=T, mode="nearest").squeeze(1)

        if fm is not None:
            msk = fm.unsqueeze(-1).type_as(hid)
            pool = (hid * msk).sum(dim=1) / msk.sum(dim=1).clamp_min(1e-6)
        else:
            pool = hid.mean(dim=1)

        lg = self.head(pool)

        if labels is not None:
            l = labels.unsqueeze(1).to(lg.dtype)
            loss = F.binary_cross_entropy_with_logits(lg, l)
            return types.SimpleNamespace(loss=loss, logits=lg)
        return types.SimpleNamespace(logits=lg)

# Load ECG-FM backbone
eckpt = os.path.join(data_dir, "mimic_iv_ecg_physionet_pretrained.pt")
bb_e = load_ecg(eckpt, dev)

# Storage for all results
all_results = []
all_histories = {}


# Hyperparameter Tuning


if TUNING_MODE:

    print("HYPERPARAMETER TUNING MODE")


    best_config = {'score': 0, 'params': {}}
    tune_results = []

    # Grid search over batch size, learning rate, weight decay
    for bs in HP_CONFIG['batch_sizes']:
        for lr in HP_CONFIG['learning_rates_adapter']:
            for wd in HP_CONFIG['weight_decays']:
                print(f"\nTesting: BS={bs}, LR={lr}, WD={wd}")

                tr_w = DataLoader(ds_tr, batch_size=bs, shuffle=True, collate_fn=cf_w)
                vl_w = DataLoader(ds_val, batch_size=bs, shuffle=False, collate_fn=cf_w)

                m_test = W2VA(enc_w).to(dev)
                m_test, hist = train(m_test, pw, tr_w, vl_w, dev, lr=lr, ep=HP_CONFIG['epochs'][0],
                                    wd=wd, pat=HP_CONFIG['patience'][0], verbose=False)

                # Score based on final accuracy + AUC
                final_acc = hist['val_acc'][-1]
                final_auc = hist['val_auc'][-1]
                score = (final_acc + final_auc) / 2

                tune_results.append({
                    'batch_size': bs,
                    'learning_rate': lr,
                    'weight_decay': wd,
                    'val_acc': final_acc,
                    'val_auc': final_auc,
                    'score': score
                })

                if score > best_config['score']:
                    best_config['score'] = score
                    best_config['params'] = {'bs': bs, 'lr': lr, 'wd': wd}

                print(f"  Val Acc: {final_acc:.4f}, Val AUC: {final_auc:.4f}, Score: {score:.4f}")

    tune_df = pd.DataFrame(tune_results).sort_values('score', ascending=False)
    tune_df.to_csv(os.path.join(met_dir, 'hyperparameter_tuning.csv'), index=False)
    print(f"\nBest Config: {best_config}")
    print(tune_df.head(10))


# Main Training Loop: Train All 6 Models

BS = 64  # Batch size

# --- Model 1: Wav2Vec2 + Adapter ---
print("\n" + "="*60)
print("MODEL 1/6: WAV2VEC2 + ADAPTER")
print("="*60)

tr_w = DataLoader(ds_tr, batch_size=BS, shuffle=True, collate_fn=cf_w)
vl_w = DataLoader(ds_val, batch_size=BS, shuffle=False, collate_fn=cf_w)
te_w = DataLoader(ds_te, batch_size=BS, shuffle=False, collate_fn=cf_w)

m_wa = W2VA(enc_w).to(dev)
trn = sum(p.numel() for p in m_wa.parameters() if p.requires_grad)
tot = sum(p.numel() for p in m_wa.parameters())
print(f"Trainable params: {trn:,} / {tot:,} ({100*trn/tot:.4f}%)")

m_wa, h_wa = train(m_wa, pw, tr_w, vl_w, dev, lr=5e-5, ep=10, wd=1e-4, pat=3)
r_wa_v = eval_mdl(m_wa, pw, vl_w, dev)
r_wa_t = eval_mdl(m_wa, pw, te_w, dev)
print(f"\nResults: Val Acc={r_wa_v['acc']:.4f} F1={r_wa_v['f1']:.4f} AUC={r_wa_v['auc']:.4f}")
print(f"         Test Acc={r_wa_t['acc']:.4f} F1={r_wa_t['f1']:.4f} AUC={r_wa_t['auc']:.4f}")

save_hist(h_wa, "Wav2Vec2_Adapter")
plot_training_curves(h_wa, "Wav2Vec2_Adapter")
all_histories['Wav2Vec2+Adapter'] = h_wa
all_results.append(('Wav2Vec2', 'Adapter', r_wa_v, r_wa_t))

# --- Model 2: Wav2Vec2 + LoRA ---
print("\n" + "="*60)
print("MODEL 2/6: WAV2VEC2 + LORA")
print("="*60)

cfg_w = AutoConfig.from_pretrained(wm, num_labels=1, problem_type="single_label_classification")
base_w = Wav2Vec2ForSequenceClassification.from_pretrained(wm, config=cfg_w).to(dev)
base_w.enable_input_require_grads = noop.__get__(base_w, type(base_w))

lora_w = LoraConfig(r=8, lora_alpha=16, lora_dropout=0.10,
                    target_modules=["q_proj", "k_proj", "v_proj", "out_proj"])
m_wl = get_peft_model(base_w, lora_w).to(dev)
m_wl.print_trainable_parameters()

# Patch forward method for BCE loss
if not hasattr(m_wl, "_orig_forward"):
    m_wl._orig_forward = m_wl.forward

def fwd_w(self, **kw):
    l = kw.pop("labels", None)
    out = self._orig_forward(**kw)
    lg = out.logits if hasattr(out, "logits") else out
    if l is not None:
        ll = l.unsqueeze(1).to(lg.dtype)
        loss = F.binary_cross_entropy_with_logits(lg, ll)
        return type("O", (), {"loss": loss, "logits": lg})
    return type("O", (), {"logits": lg})

m_wl.forward = types.MethodType(fwd_w, m_wl)

m_wl, h_wl = train(m_wl, pw, tr_w, vl_w, dev, lr=2.5e-5, ep=10, wd=1e-4, pat=3)
r_wl_v = eval_mdl(m_wl, pw, vl_w, dev)
r_wl_t = eval_mdl(m_wl, pw, te_w, dev)
print(f"\nResults: Val Acc={r_wl_v['acc']:.4f} F1={r_wl_v['f1']:.4f} AUC={r_wl_v['auc']:.4f}")
print(f"         Test Acc={r_wl_t['acc']:.4f} F1={r_wl_t['f1']:.4f} AUC={r_wl_t['auc']:.4f}")

save_hist(h_wl, "Wav2Vec2_LoRA")
plot_training_curves(h_wl, "Wav2Vec2_LoRA")
all_histories['Wav2Vec2+LoRA'] = h_wl
all_results.append(('Wav2Vec2', 'LoRA', r_wl_v, r_wl_t))

# --- Model 3: HuBERT + Adapter ---
print("\n" + "="*60)
print("MODEL 3/6: HUBERT + ADAPTER")
print("="*60)

tr_h = DataLoader(ds_tr, batch_size=BS, shuffle=True, collate_fn=cf_h)
vl_h = DataLoader(ds_val, batch_size=BS, shuffle=False, collate_fn=cf_h)
te_h = DataLoader(ds_te, batch_size=BS, shuffle=False, collate_fn=cf_h)

m_ha = HBA(enc_h).to(dev)
trn = sum(p.numel() for p in m_ha.parameters() if p.requires_grad)
tot = sum(p.numel() for p in m_ha.parameters())
print(f"Trainable params: {trn:,} / {tot:,} ({100*trn/tot:.4f}%)")

m_ha, h_ha = train(m_ha, ph, tr_h, vl_h, dev, lr=5e-5, ep=10, wd=1e-4, pat=3)
r_ha_v = eval_mdl(m_ha, ph, vl_h, dev)
r_ha_t = eval_mdl(m_ha, ph, te_h, dev)
print(f"\nResults: Val Acc={r_ha_v['acc']:.4f} F1={r_ha_v['f1']:.4f} AUC={r_ha_v['auc']:.4f}")
print(f"         Test Acc={r_ha_t['acc']:.4f} F1={r_ha_t['f1']:.4f} AUC={r_ha_t['auc']:.4f}")

save_hist(h_ha, "HuBERT_Adapter")
plot_training_curves(h_ha, "HuBERT_Adapter")
all_histories['HuBERT+Adapter'] = h_ha
all_results.append(('HuBERT', 'Adapter', r_ha_v, r_ha_t))

# --- Model 4: HuBERT + LoRA ---
print("\n" + "="*60)
print("MODEL 4/6: HUBERT + LORA")
print("="*60)

cfg_h = AutoConfig.from_pretrained(hm, num_labels=1, problem_type="single_label_classification")
base_h = HubertForSequenceClassification.from_pretrained(hm, config=cfg_h).to(dev)
base_h.enable_input_require_grads = noop.__get__(base_h, type(base_h))

lora_h = LoraConfig(r=8, lora_alpha=16, lora_dropout=0.10,
                    target_modules=["q_proj", "k_proj", "v_proj", "out_proj"])
m_hl = get_peft_model(base_h, lora_h).to(dev)
m_hl.print_trainable_parameters()

if not hasattr(m_hl, "_orig_forward"):
    m_hl._orig_forward = m_hl.forward

def fwd_h(self, **kw):
    l = kw.pop("labels", None)
    out = self._orig_forward(**kw)
    lg = out.logits if hasattr(out, "logits") else out
    if l is not None:
        ll = l.unsqueeze(1).to(lg.dtype)
        loss = F.binary_cross_entropy_with_logits(lg, ll)
        return type("O", (), {"loss": loss, "logits": lg})
    return type("O", (), {"logits": lg})

m_hl.forward = types.MethodType(fwd_h, m_hl)

m_hl, h_hl = train(m_hl, ph, tr_h, vl_h, dev, lr=2.5e-5, ep=10, wd=1e-4, pat=3)
r_hl_v = eval_mdl(m_hl, ph, vl_h, dev)
r_hl_t = eval_mdl(m_hl, ph, te_h, dev)
print(f"\nResults: Val Acc={r_hl_v['acc']:.4f} F1={r_hl_v['f1']:.4f} AUC={r_hl_v['auc']:.4f}")
print(f"         Test Acc={r_hl_t['acc']:.4f} F1={r_hl_t['f1']:.4f} AUC={r_hl_t['auc']:.4f}")

save_hist(h_hl, "HuBERT_LoRA")
plot_training_curves(h_hl, "HuBERT_LoRA")
all_histories['HuBERT+LoRA'] = h_hl
all_results.append(('HuBERT', 'LoRA', r_hl_v, r_hl_t))

# --- Model 5: ECG-FM + Adapter ---
print("\n" + "="*60)
print("MODEL 5/6: ECG-FM + ADAPTER")
print("="*60)

m_ea = ECA(bb_e).to(dev)
trn = sum(p.numel() for p in m_ea.parameters() if p.requires_grad)
tot = sum(p.numel() for p in m_ea.parameters())
print(f"Trainable params: {trn:,} / {tot:,} ({100*trn/tot:.4f}%)")

m_ea, h_ea = train(m_ea, pw, tr_w, vl_w, dev, lr=5e-5, ep=10, wd=1e-4, pat=3)
r_ea_v = eval_mdl(m_ea, pw, vl_w, dev)
r_ea_t = eval_mdl(m_ea, pw, te_w, dev)
print(f"\nResults: Val Acc={r_ea_v['acc']:.4f} F1={r_ea_v['f1']:.4f} AUC={r_ea_v['auc']:.4f}")
print(f"         Test Acc={r_ea_t['acc']:.4f} F1={r_ea_t['f1']:.4f} AUC={r_ea_t['auc']:.4f}")

save_hist(h_ea, "ECG-FM_Adapter")
plot_training_curves(h_ea, "ECG-FM_Adapter")
all_histories['ECG-FM+Adapter'] = h_ea
all_results.append(('ECG-FM', 'Adapter', r_ea_v, r_ea_t))

# --- Model 6: ECG-FM + LoRA ---
print("\n" + "="*60)
print("MODEL 6/6: ECG-FM + LORA")
print("="*60)

m_el = ECL(bb_e).to(dev)
trn = sum(p.numel() for p in m_el.parameters() if p.requires_grad)
tot = sum(p.numel() for p in m_el.parameters())
print(f"Trainable params: {trn:,} / {tot:,} ({100*trn/tot:.4f}%)")

m_el, h_el = train(m_el, pw, tr_w, vl_w, dev, lr=2.5e-5, ep=10, wd=1e-4, pat=3)
r_el_v = eval_mdl(m_el, pw, vl_w, dev)
r_el_t = eval_mdl(m_el, pw, te_w, dev)
print(f"\nResults: Val Acc={r_el_v['acc']:.4f} F1={r_el_v['f1']:.4f} AUC={r_el_v['auc']:.4f}")
print(f"         Test Acc={r_el_t['acc']:.4f} F1={r_el_t['f1']:.4f} AUC={r_el_t['auc']:.4f}")

save_hist(h_el, "ECG-FM_LoRA")
plot_training_curves(h_el, "ECG-FM_LoRA")
all_histories['ECG-FM+LoRA'] = h_el
all_results.append(('ECG-FM', 'LoRA', r_el_v, r_el_t))


# Results Summary & Visualization


print("FINAL RESULTS SUMMARY")


# Create summary table
summ = pd.DataFrame([
    ["Wav2Vec2+Adapter", r_wa_v["acc"], r_wa_v["f1"], r_wa_v["auc"], r_wa_t["acc"]],
    ["Wav2Vec2+LoRA", r_wl_v["acc"], r_wl_v["f1"], r_wl_v["auc"], r_wl_t["acc"]],
    ["HuBERT+Adapter", r_ha_v["acc"], r_ha_v["f1"], r_ha_v["auc"], r_ha_t["acc"]],
    ["HuBERT+LoRA", r_hl_v["acc"], r_hl_v["f1"], r_hl_v["auc"], r_hl_t["acc"]],
    ["ECG-FM+Adapter", r_ea_v["acc"], r_ea_v["f1"], r_ea_v["auc"], r_ea_t["acc"]],
    ["ECG-FM+LoRA", r_el_v["acc"], r_el_v["f1"], r_el_v["auc"], r_el_t["acc"]],
], columns=["Model", "Val_Acc", "Val_F1", "Val_AUC", "Test_Acc"])
print("\n", summ.to_string(index=False))

sp = os.path.join(base, "results.csv")
summ.to_csv(sp, index=False)
print(f"\nSaved summary: {sp}")

# Detailed results with all metrics
def pr(m, mt, sp, mr):
    return {
        "Model": m,
        "PEFT": mt,
        "Split": sp,
        "Accuracy": mr.get("acc", float("nan")),
        "Precision": mr.get("precision", float("nan")),
        "Recall": mr.get("recall", float("nan")),
        "F1": mr.get("f1", float("nan")),
        "AUC": mr.get("auc", float("nan"))
    }

det = pd.DataFrame([
    pr("Wav2Vec2", "Adapter", "Val", r_wa_v), pr("Wav2Vec2", "Adapter", "Test", r_wa_t),
    pr("Wav2Vec2", "LoRA", "Val", r_wl_v), pr("Wav2Vec2", "LoRA", "Test", r_wl_t),
    pr("HuBERT", "Adapter", "Val", r_ha_v), pr("HuBERT", "Adapter", "Test", r_ha_t),
    pr("HuBERT", "LoRA", "Val", r_hl_v), pr("HuBERT", "LoRA", "Test", r_hl_t),
    pr("ECG-FM", "Adapter", "Val", r_ea_v), pr("ECG-FM", "Adapter", "Test", r_ea_t),
    pr("ECG-FM", "LoRA", "Val", r_el_v), pr("ECG-FM", "LoRA", "Test", r_el_t),
])

dp = os.path.join(base, "detailed.csv")
det.to_csv(dp, index=False)
print(f"Saved detailed: {dp}")

# Comparison curves across all models

print("GENERATING COMPARISON CURVES")


plot_comparison_curves(all_histories, 'val_acc')
plot_comparison_curves(all_histories, 'val_loss')
plot_comparison_curves(all_histories, 'val_f1')
plot_comparison_curves(all_histories, 'val_auc')
print("Comparison curves saved")

# Confusion matrices

print("GENERATING CONFUSION MATRICES")


def plot_cm(cm, cn=("Negative", "Positive"), t="Confusion Matrix"):
    """Plot confusion matrix with counts and percentages"""
    cm = np.array(cm, dtype=np.float64)
    rs = cm.sum(axis=1, keepdims=True)
    rs[rs == 0] = 1.0
    cp = cm / rs

    fig, ax = plt.subplots(figsize=(6, 5))
    im = ax.imshow(cm, interpolation='nearest', cmap='Blues')
    ax.set_title(t, fontsize=14, fontweight='bold')
    plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)

    ax.set_xticks(np.arange(len(cn)))
    ax.set_yticks(np.arange(len(cn)))
    ax.set_xticklabels(cn)
    ax.set_yticklabels(cn)
    ax.set_ylabel("True Label", fontsize=12)
    ax.set_xlabel("Predicted Label", fontsize=12)

    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            ax.text(j, i, f"{int(cm[i, j])}\n({cp[i, j]*100:.1f}%)",
                   ha="center", va="center", fontsize=11,
                   color="white" if cm[i, j] > cm.max() / 2 else "black")

    fig.tight_layout()
    save_fig(fig, t)
    plt.close()

cms = [
    (r_wa_v["cm"], "Wav2Vec2_Adapter_Val"),
    (r_wl_v["cm"], "Wav2Vec2_LoRA_Val"),
    (r_ha_v["cm"], "HuBERT_Adapter_Val"),
    (r_hl_v["cm"], "HuBERT_LoRA_Val"),
    (r_ea_v["cm"], "ECGFM_Adapter_Val"),
    (r_el_v["cm"], "ECGFM_LoRA_Val"),
]

for cm, t in cms:
    plot_cm(cm, ("Negative", "Positive"), t)
    print(f"Saved: {t}")

print(f"\nAll confusion matrices saved to: {plot_dir}")

# Final summary

print("TRAINING COMPLETE!")

print(f"\nAll outputs saved to: {base}")
print(f"  ├── results.csv           - Summary table")
print(f"  ├── detailed.csv          - Full metrics by split")
print(f"  ├── plots/                - Training curves & confusion matrices")
print(f"  └── histories/            - Per-epoch training logs")
